openapi: 3.0.0
info:
  version: 1.1.0
  title: Whisper
  description: WHISPER OPENAPI DOCS
servers:
  - url: 'http://{host}:{port}/api/{basePath}'
    description: API SERVER
    variables:
      host:
        default: localhost
      port:
        default: '3000'
      basePath:
        default: v1
tags:
  - name: Users
paths:
  /users:
    x-swagger-router-controller: user
    get:
      tags:
        - Users
      description: Get all Users
      operationId: getUsers
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                    flags:
                      type: integer
                      enum:
                        - 0
                        - 1 << 0
                        - 1 << 1
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      tags:
        - Users
      description: Create new User
      operationId: postUsers
      requestBody:
        description: User to be created
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                flags:
                  type: integer
                  enum:
                    - 0
                    - 1 << 0
                    - 1 << 1
      responses:
        '201':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  username:
                    type: string
                  password:
                    type: string
                  flags:
                    type: integer
                    enum:
                      - 0
                      - 1 << 0
                      - 1 << 1
          description: Created
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  '/users/{userId}':
    x-swagger-router-controller: user
    parameters:
      - in: path
        name: userId
        description: The ID of User to retrieve
        required: true
        schema:
          type: string
    get:
      tags:
        - Users
      description: Get User by ID
      operationId: getUser
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  username:
                    type: string
                  password:
                    type: string
                  flags:
                    type: integer
                    enum:
                      - 0
                      - 1 << 0
                      - 1 << 1
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      tags:
        - Users
      description: Update User by ID
      operationId: putUser
      requestBody:
        description: User to be updated
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                flags:
                  type: integer
                  enum:
                    - 0
                    - 1 << 0
                    - 1 << 1
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  username:
                    type: string
                  password:
                    type: string
                  flags:
                    type: integer
                    enum:
                      - 0
                      - 1 << 0
                      - 1 << 1
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags:
        - Users
      description: Remove User by ID
      operationId: deleteUser
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /swagger:
    x-swagger-pipe: swagger_raw
components:
  schemas:
    User:
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        password:
          type: string
        flags:
          type: integer
          enum:
            - 0
            - 1 << 0
            - 1 << 1
  parameters:
    userId:
      - in: path
        name: userId
        description: The ID of User to retrieve
        required: true
        schema:
          type: string
  responses:
    404NotFound:
      description: Not Found
    500InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    200OK:
      description: OK
    422UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    201Created:
      description: Created
    204NoContent:
      description: No Content
